# Generated by Django 5.1.1 on 2025-01-16 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sapp', '0005_category_type_alter_transaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorybudget',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Sapp.category'),
        ),
    ]
